.MODEL SMALL
.STACK 100H
.DATA
STRING DB "HEllO wORDL$"
PROMPT1 DB "VOWEL COUNT: $"
PROMPT2 DB "CONSONENT COUNT: $"
PROMPT3 DB "WORD COUNT: $"
VOWEL DB 30H
WORD DB 31H
CONSONENT DB 30H

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    CALL COUNT
VOWEL_PRINT:
    MOV AH,9
    LEA DX,PROMPT1
    INT 21H
    CMP VOWEL,39H
    JG VOWEL10
    MOV AH,2
    MOV DL,VOWEL
    INT 21H
    
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H
    JMP CONSONENT_PRINT
VOWEL10:
    MOV AH,2
    MOV DL,31H
    INT 21H
    SUB VOWEL,39H
    ADD VOWEL,30H
    MOV DL,VOWEL
    INT 21H
    
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H
    
CONSONENT_PRINT:    
    MOV AH,9
    LEA DX,PROMPT2
    INT 21H
    CMP CONSONENT,39H
    JG CONSONENT10
    MOV AH,2
    MOV DL,CONSONENT
    INT 21H
  
    
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H
    JMP WORD_PRINT


CONSONENT10:
    MOV AH,2
    MOV DL,31H
    INT 21H
    SUB CONSONENT,39H
    ADD CONSONENT,30H
    MOV DL,CONSONENT
    INT 21H
    
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H


WORD_PRINT:    
    MOV AH,9
    LEA DX,PROMPT3
    INT 21H
    CMP WORD,39H
    JG WORD10
    MOV AH,2
    MOV DL,WORD
    INT 21H
    JMP EXIT
    
WORD10:
    MOV AH,2
    MOV DL,31H
    INT 21H
    SUB WORD,39H
    ADD WORD,30H
    MOV DL,WORD
    INT 21H
    
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H

EXIT:    
    MOV AH,4CH
    INT 21H


    MAIN ENDP



COUNT PROC
    MOV AH,9
    LEA SI,STRING
CONDITION:    
    MOV DL,[SI]
    CMP DL,24H
    JE VOWEL_PRINT
    
    CMP DL,41H
    JE VOWEL_COUNT
    CMP DL,45H
    JE VOWEL_COUNT
    CMP DL,49H
    JE VOWEL_COUNT ;VOWEL UPPER
    CMP DL,4FH
    JE VOWEL_COUNT
    CMP DL,55H
    JE VOWEL_COUNT
    
    
    CMP DL,61H
    JE VOWEL_COUNT
    CMP DL,65H
    JE VOWEL_COUNT
    CMP DL,69H
    JE VOWEL_COUNT ;VOWEL LOWER
    CMP DL,6FH
    JE VOWEL_COUNT
    CMP DL,75H
    JE VOWEL_COUNT
    
    
    CMP DL,20H
    JE SPACE_COUNT
    
    ADD CONSONENT,1
    INC SI
    JMP CONDITION
    
VOWEL_COUNT:
    ADD VOWEL,1
    INC SI
    JMP CONDITION
    
    
SPACE_COUNT:
    ADD WORD,1
    INC SI
    JMP CONDITION
   RET    
   COUNT ENDP

END MAIN